#!/usr/bin/env bash

#Keyboard layout. Keyboard shortcut (Ctrl+Shift) ENG, RUS.
keyboard_layout_ () {
    if [[ "$IDENTIFIER" = "unicode" ]]; then
        if [[ "$(xset -q | grep "LED mask:" | awk '{ print $10 }')" == "00000000" ]]; then
            printf "%s" "ENG "
        else
            printf "%s" "RUS "
        fi
    fi
}

keyboard_layout_
